### PR TITLE
Webpack 4

### PR DESCRIPTION
**Pull request by chenxsan**
@TheLarkInn I'm wondering if this pull request is what you want someone to do here https://github.com/jantimon/html-webpack-plugin/pull/823#issuecomment-365070707?

### CODE REVIEW

**Comment by Graham42** [comment]
This needs some changes to handle the new common chunk behaviour introduce in alpha-5. As it is, it likely wont work. I'll try and take a look at this tonight.

**Comment by chenxsan** [comment]
Cool.

**Comment by TheLarkInn** [comment]
@Graham42 @chenxsan Hey there!!! For a few upstream reasons I was hoping to land this work today or tomorrow to publish. If you don't think you can get this done today/evening ( no pressure ), please let me know!!! That way I can get a few resources or contributors to team up on it and we can git r dun.

**Comment by Graham42** [comment]
I'm looking at this right now :slightly_smiling_face: will post back in an hour or so with progress

**Comment by TheLarkInn** [comment]
No worries at all, thanks so much for the responsiveness. In fact, could you shoot me your email, I'd like to shoot something over to you also.

**Comment by Graham42** [comment]
Email sent in twitter DM

**Comment by TheLarkInn** [comment]
tytyty

**Comment by Graham42** [comment]
Update: Making progress. Currently refactoring the internal dependency sort to handle chunkgroups.

**Pull request closed without merging**
